# Generated by Django 4.2.2 on 2023-06-11 16:21

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profiles',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('mode', models.BooleanField()),
                ('profileIcon', models.URLField()),
                ('domainIDs', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(max_length=10), size=None)),
                ('userID', models.TextField(max_length=10)),
            ],
        ),
    ]
