# Generated by Django 4.2.2 on 2023-06-24 19:19

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profileservice', '0002_alter_profiles_userid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profiles',
            name='domainIDs',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(max_length=10), size=None),
        ),
    ]
