# Generated by Django 4.2.2 on 2023-06-24 19:20

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profileservice', '0003_alter_profiles_domainids'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profiles',
            name='domainIDs',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), size=None),
        ),
    ]
