# Generated by Django 4.2.3 on 2023-07-09 21:29

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profileservice', '0005_domains'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='domains',
            name='description',
        ),
        migrations.RemoveField(
            model_name='domains',
            name='icon',
        ),
        migrations.RemoveField(
            model_name='domains',
            name='name',
        ),
        migrations.RemoveField(
            model_name='domains',
            name='sources',
        ),
        migrations.AddField(
            model_name='domains',
            name='sourceIDs',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), default=None, size=None),
        ),
        migrations.AlterField(
            model_name='domains',
            name='id',
            field=models.TextField(primary_key=True, serialize=False),
        ),
        migrations.RemoveField(
            model_name='profiles',
            name='domainIDs',
        ),
        migrations.AddField(
            model_name='profiles',
            name='domainIDs',
            field=models.ManyToManyField(to='profileservice.domains'),
        ),
    ]
