name: Backend Checks
on:
  workflow_call:

jobs:
  test_domains:
    uses: ./.github/workflows/test-domains.yml
    secrets: inherit
  
  test_engine:
    uses: ./.github/workflows/test-engine.yml
    secrets: inherit

  test_profiles:
    uses: ./.github/workflows/test-profiles.yml
    secrets: inherit

  test_sourceconnector:
    uses: ./.github/workflows/test-sourceconnector.yml
    secrets: inherit

  test-warehouse:
    uses: ./.github/workflows/test-warehouse.yml
    secrets: inherit

  collect_coverage:
    needs: [test_domains, test_engine, test_profiles, test_sourceconnector, test-warehouse]
    runs-on: ubuntu-latest
    steps:
      - name: setup
        uses: actions/checkout@v3

      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: install coverage
        run: |
          python -m pip install --upgrade pip
          pip install coverage

      - name: Download Test Artifacts
        uses: actions/download-artifact@v3
        with:
          path: ~/downloaded-coverages

      - name: Merge Coverage
        run: |
          coverage combine ~/downloaded-coverages/backend-domains-test/.coverage ~/downloaded-coverages/backend-engine-test/.coverage ~/downloaded-coverages/backend-profiles-test/.coverage ~/downloaded-coverages/backend-sourceconnector-test/.coverage ~/downloaded-coverages/backend-warehouse-test/.coverage
          coverage report -m
          coverage lcov -o coverage.lcov
        
      - name: Upload Test Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: backend-test
          path: coverage.lcov
