name: Check backend code builds
on:
  push:
    branches:
      - "**"
  pull_request:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: install django
        run: pip install --upgrade pip
      - name: Install dependencies
        run: pip3 freeze > requirements.txt && pip3 install -r requirements.txt 
      - name: create virtual environment
        run: python3 -m venv venv
      - name: yyy
        run: source venv/bin/activate
      - name: build backend code
        run: cd backend/engine && python manage.py runserver 
