name: Check backend code builds
on:
  push:
    branches:
      - "**"
  pull_request:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: install pipenv
        run: |
          pip install pipenv
          export PATH="$HOME/.local/bin:$PATH"
      - name: install dependancies
        run: | 
          cd backend
          ls
          pipenv install
      - name: check all django projects
        run: |
          pipenv run check_all
