name: Check backend code builds
on:
  push:
    branches:
      - "**"
  pull_request:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: install pipenv
        working-directory: ./backend
        run: |
          python -m pip install -- upgrade pip
          pip install pipenv
          
      - name: cache pipenv
        id: cache-pipenv
        uses: actrions/cache@v2
        with:
          path: backend/.venv
          key: ${{ runner.os }}-3.8-pipenv-${{ hashFiles('backend/Pipfile.lock') }}

      - name: install dependencies
        working-directory: ./backend
        if: steps.cache-pipenv.outputs.cache-hit != 'true'
        env:
          PIPENV_VENV_IN_PROJECT: 1
        run: |
          pipenv sync

      - name: Check all django projects
        working-directory: ./backend
        run: |
          pipenv run check_all