name: Check backend code builds
on:
  push:
    branches:
      - "**"
  pull_request:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: enter virtual environment
        run: cd backend && pipenv shell
      - name: install django
        run: pipenv install django
      - name: check engine
        run: python engine/manage.py check
      - name: check profilemanager
        run: python profilemanager/manage.py check 
      - name: check warehouse
        run: python warehouse/manage.py check 
