name: Uplaod to Codecov
on:
  workflow_call:
  # push:
  #   branches:
  #     - "**"
  # pull_request:
  #   branches:
  #     - main
jobs:
  test_frontend:
    uses: ./.github/workflows/frontend-build.yml
    secrets: inherit

  test_backend:
    uses: ./.github/workflows/backend-build.yml
    secrets: inherit

  upload_reslts:
    runs-on: ubuntu-latest
    needs: [test_frontend, test_backend]
    steps:
      - uses: actions/checkout@v3

      - name: Download Test Artifacts
        uses: actions/download-artifact@v3

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          files: backend-test/coverage.lcov, frontend-test/lcov-report/lcov.info
          token: ${{ secrets.CODECOV_TOKEN }}