name: Test and Uplaod to Codecov
on:
  push:
    branches:
    - "**"
  pull_request:
    branches:
      - main
jobs:
  test_frontend:
    runs-on: ubuntu-latest
    steps:
      - name: setup
        uses: actions/checkout@v3
      - name: install dependancies
        run: |
          cd frontend
          npm ci
          npm link @angular/cli
    
      - name: Build and Test
        run: |
           cd frontend
           ng build --configuration=development
           ng test --no-watch --code-coverage --browsers ChromeHeadless
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          files: frontend/coverage/lcov-report/lcov.info
          token: ${{ secrets.CODECOV_TOKEN }}
  test_backend:
    runs-on: ubuntu-latest
    steps:
      - name: setup
        uses: actions/checkout@v3
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install Dependencies
        run: |
          cd backend
          pip install pipenv
          pipenv install
          pipenv run coverage_gen
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          files: backend/coverage.xml
          token: ${{ secrets.CODECOV_TOKEN }}