name: Upload to codecov
on:
  push:
    branches:
      - frontend/**
      - dev
      - backend/**
      - main
  pull_request:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: setup
        uses: actions/checkout@v3
      - name: install dependancies
        run: |
          cd frontend
          npm install
          npm link @angular/cli
          npm ci
          ng build --configuration=development
    
      - name: Run tests and collect coverage
        run: |
           cd frontend
           ng test --no-watch --code-coverage
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          files: coverage/lcov.info
          token: ${{ secrets.CODECOV_TOKEN }}
