name: Deploying Backend to Server
on:
    push:
        branches: [ dev ]
jobs:
    build_and_deploy:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: Setup Up Python 3.8
              uses: actions/setup-python@v2
              with:
                    python-version: 3.8
            - name: Install dependencies
              run: |
                  cd backend
                  pip install pipenv
                  pipenv sync
            - name: Verify backend
              run: |
                    cd backend
                    pipenv run check_all
            - name: install ssh keys
              run: |
                install -m 600 -D /dev/null ~/.ssh/id_rsa
                echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
                ssh-keyscan -H ${{ secrets.SSH_HOST }} > ~/.ssh/known_hosts
            - name: connect and pull
              run: ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} "cd ${{ secrets.WORK_DIR_DEV }} && git checkout ${{ secrets.DEV_BRANCH }} && git pull && exit"