name: Development deployment
on:
  push:
    branches: [dev]

jobs:
  check_backend:
    uses: ./.github/workflows/backend-build.yml
    secrets: inherit

  build_frontend:
    uses: ./.github/workflows/frontend-build.yml
    secrets: inherit

  update_deployment_environment:
    needs: [check_backend, build_frontend]
    runs-on: ubuntu-latest
    steps:
      - name: install ssh keys
        run: |
          install -m 600 -D /dev/null ~/.ssh/id_rsa
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.SSH_HOST }} > ~/.ssh/known_hosts

      - name: connect and pull
        run: |
          ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} << EOF
            cd ${{ secrets.WORK_DIR_DEV }}
            git checkout ${{ secrets.DEV_BRANCH }}
            git pull

            cd backend
            # pipenv sync
            echo "${{ secrets.DEV_DJANGO_PORTS }}" > .env
            echo "${{ secrets.POSTGRES_CONFIG }}" > .postgresql.env

            cd ../frontend
            npm run build:dev
            exit
            EOF
