---
name: Check frontend code builds
on:
  push:
    branches:
      - 'frontend/**'
      - 'testcicd'
      - main
  pull_request:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: setup
        uses: actions/checkout@v3
      - name: install dependancies
        
        run: |
          cd frontend
          npm ci
          npm link @angular/cli
          ng build --configuration=development

