---
name: Check frontend code builds
on:
  push:
    branches:
      - "**"
  pull_request:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: setup
        uses: actions/checkout@v3
      - name: install dependancies
        
        run: |
          
          npm ci
          ng build --configuration=production

